package edu.uci.ics.archtrace.connectors;

/**
 * Listen for connection events generated by the connectors
 *
 * @author Leo Murta (murta@ics.uci.edu, murta@cos.ufrj.br) - Jul 29, 2004
 */
public interface ConnectionListener {

	/**
	 * Indicates that the connector just start a "transaction" with its counterpart
	 */
	public void connectionStarted(String message);
	
	/**
	 * Indicates the progress of the conection
	 */
	public void connectionProgress(String message);
	
	/**
	 * Indicates that the connector just finished a "transaction" with its counterpart
	 */
	public void connectionFinished(String message);
}
